version: '3.6'

services:
  chatgpt:
    image: ghcr.io/ivanfioravanti/chatbot-ollama:main
    ports:
      - 3000:3000
    environment:
      - DEFAULT_MODEL=codellama
      - OLLAMA_HOST=http://ollama:11434
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama/models:/ollama/models
    environment:
      - OLLAMA_MODELS=/ollama/models

# Manualy download the model
# docker-compose exec ollama ollama pull codellama 
